### ISSUE TITLE
Error installing quanttb

### ISSUE THREAD

**Issue by mezewudo** [AbeelLab/quanttb#1]
Hello:
It seems a path to the data folder in quanttb is wrongly coded in one of the build scripts. I get this error when I run the 'sudo python setup.py install' command:

"..creating build/lib.linux-x86_64-2.7/quanttb/ata
error: can't copy 'quanttb/ata/GCF_000277735.2_ASM27773v2_genomic.fna.bwt': doesn't exist or not a regular file"

it seems to depict 'data' as 'ata'. Could you look to fix.

Thanks.

**Comment by canyansi** [comment]
Hi. What kind of platform are you using? I just tried to fresh install it on a different computer and this problem is not there.

**Comment by mezewudo** [comment]
I am using Ubuntu 14.04 and have python 2.7.16 installed. I cloned the repo
from github for the installation.

**Comment by canyansi** [comment]
I tried to fresh install using a macbook, centos and an ubuntu and it seems to install properly. I am having a difficult time reproducing this error that you're getting.

**Comment by sandergoossens** [comment]
Hi: 
I am having the exact same problem as mezewudo
Could you try to find it back in your code and fix it?

**Comment by thomasabeel** [comment]
It appears to be correct in the code and worked on several fresh installs with different machines. We have no way to reproduce this problem. However, while testing, I discovered another problem with the install script. I wonder whether the fix for that one also fixes this one. 
https://github.com/AbeelLab/quanttb/tree/thomasabeel-patch-1

**Comment by thomasabeel** [comment]
Sander can you test whether this resolves your problem?

**Comment by sandergoossens** [comment]
Dag Thomas,

hij geeft de foutmelding niet meer,

bedankt!


Sander

________________________________
Van: Thomas Abeel <notifications@github.com>
Verzonden: woensdag 25 maart 2020 12:52:22
Aan: AbeelLab/quanttb
CC: Sander Goossens; Comment
Onderwerp: Re: [AbeelLab/quanttb] Error installing quanttb (#1)


Sander can you test whether this resolves your problem?
