### ISSUE TITLE
Race condition in parallel use

### ISSUE THREAD

**Issue by pgcudahy** [AbeelLab/quanttb#3]
Thanks for the great new tool. I've been experimenting with it in a pipeline manager (similar to snakemake) that will run instances of `quanttb` in parallel, but in the code for quanttb.py the section
```
qtobj.temp = qtobj.outdirr + "/temp"
    if not os.path.isdir(qtobj.temp):
        os.makedirs(qtobj.temp)
```
can sometimes throw an error if in-between the check for the temp directory and its creation, another thread goes ahead and creates a temp directory

I think a solution is at https://stackoverflow.com/questions/1586648/ to use 
```
qtobj.temp = qtobj.outdirr + "/temp"
try:
    os.mkdirs(qtobj.temp)
except OSError as e:
    if e.errno == errno.EEXIST and os.path.isdir(qtobj.temp):
        # File exists, and it's a directory,
        # another process beat us to creating this dir, that's OK.
        pass
    else:
        # Our target dir exists as a file, or different error,
        # reraise the error!
        raise
```

Best,
Patrick

**Comment by canyansi** [comment]
Thanks! Will implement it.
