### ISSUE TITLE
Can quantTB be used to identify strains of other species?

### ISSUE THREAD

**Issue by liaoherui** [AbeelLab/quanttb#5]
Hi, 
I am trying to build a snp database with many assembly genomes of one RNA virus as the tutorial step said.
I am using the command: `quanttb makesnpdb  -g ....`
But always with the problem:

![image](https://user-images.githubusercontent.com/22760266/90779380-59a2d380-e330-11ea-9fea-a513a3eb368c.png)

I found the *.snps files already generated in the folder "output/temp", but still with this problem. 

So, Can quantTB be used to identify strains of other species? Or, it's just designed for Mycobacterium tuberculosis?

**Comment by canyansi** [comment]
At the moment, QuantTB can only be used with Mycobacterium tuberculosis.
