### ISSUE TITLE
Issue with makesnpdb command

### ISSUE THREAD

**Issue by BrinthaVP** [AbeelLab/quanttb#6]
Hai 

I am trying to build an SNP database using the makesnpdb command for an input of 2 MTb fasta files. But I am getting the following error.
![error](https://user-images.githubusercontent.com/51736151/103064443-fffe2e80-45d9-11eb-8c08-79a37aec3864.png)

Even facing issues with respect to VCF files as well.

Thanks

**Comment by canyansi** [comment]
It seems like you're inputting fasta files, but the makesnpdb command needs .vcf files made in pilon to work. You can first make vcf files using quanttb of those fasta files that you have, then you can use the made vcffiles to make a snpdb

**Comment by BrinthaVP** [comment]
Tried to run the makesnpdb command using the vcf files generated using quantTB and getting the following error.

![image](https://user-images.githubusercontent.com/51736151/127491681-c66d5e7f-0eb5-41af-8bd9-a71990a1ff86.png)
