### ISSUE TITLE
error installing quanttb

### ISSUE THREAD

**Issue by BettyAC** [AbeelLab/quanttb#7]
I am getting the below error yet I have scipy installed 

Installed /usr/lib/python2.7/site-packages/quanttb-0.1dev-py2.7.egg
Processing dependencies for quanttb==0.1dev
Searching for scipy==1.1.0
Reading https://pypi.python.org/simple/scipy/
Couldn't retrieve index page for 'scipy'
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for scipy==1.1.0
error: Could not find suitable distribution for Requirement.parse('scipy==1.1.0')

**Comment by pvanheus** [comment]
This conda-based install procedure works for installing QuantTB. It assumes that you have a conda environment already installed.

1. Create a conda environment using `conda create -n quanttb -y python=2.7 pip scipy numpy subprocess32 bwa samtools openjdk` (or use `mamba create` if you have [mamba](https://github.com/mamba-org/mamba) installed.
2. Download the QuantTB 1.01 release from [here](https://github.com/AbeelLab/quanttb/archive/refs/tags/1.01.tar.gz).
3. Unpack the release (`tar -xf 1.01.tar.gz`) and cd into the software directory (`cd quanttb-1.01/`)
4. Install like this: `python -m pip install --no-deps --ignore-installed .`

This  will give you an install of QuantTB with dependencies managed by conda. To use this, activate the conda environment before using the command (activate with `conda activate quanttb`).

**Comment by BettyAC** [comment]
Thank you Peter, works fine now!

**Comment by justicengom** [comment]
Hi 
After following step from @pvanheus comment, I wanted to check if Quanttb is running well with data from exdata.
this is the first message from my screen :
Getting bam file and pileup for exdata/readset1.fq exdata/readset2.fq
ERROR: Some sample files don't exist:
output1/temp/readset1.vcf

then I went through the document :
cat readset1.log 
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 396040 sequences (40000040 bp)...
[M::process] read 38846 sequences (3923446 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 193080, 42, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (192, 198, 205)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (166, 231)
[M::mem_pestat] mean and std.dev: (198.49, 9.98)
[M::mem_pestat] low and high boundaries for proper pairs: (153, 244)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (3, 11, 383)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1143)
[M::mem_pestat] mean and std.dev: (75.00, 150.93)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1523)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 396040 reads in 33.368 CPU sec, 8.406 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 18958, 8, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (191, 198, 205)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (163, 233)
[M::mem_pestat] mean and std.dev: (198.39, 10.02)
[M::mem_pestat] low and high boundaries for proper pairs: (149, 247)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 38846 reads in 4.592 CPU sec, 1.022 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 /home/justicengom/miniconda3/envs/quanttb/lib/python2.7/site-packages/quanttb/data/GCF_000277735.2_ASM27773v2_genomic.fna exdata/readset1.fq exdata/readset2.fq
[main] Real time: 10.048 sec; CPU: 38.558 sec
java.util.zip.ZipException: invalid entry CRC (expected 0xdb44c871 but got 0x3ec1653d)
	at java.base/java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:408)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
	at java.base/java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:119)
	at java.base/java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
	at java.base/java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
	at com.simontuffs.onejar.Boot.findJarEntry(Boot.java:443)
	at com.simontuffs.onejar.Boot.getMyJarPath(Boot.java:415)
	at com.simontuffs.onejar.Boot.run(Boot.java:232)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Boot: Warning: jar=null loaded from java.class.path (/home/justicengom/miniconda3/envs/quanttb/lib/python2.7/site-packages/quanttb/data/pilon-1.22.jar)
Exception in thread "main" java.lang.IllegalArgumentException: Unable to locate com.simontuffs.onejar.Boot in the java.class.path: consider using -Done-jar.jar.path to specify the one-jar filename.
	at com.simontuffs.onejar.Boot.getMyJarPath(Boot.java:434)
	at com.simontuffs.onejar.Boot.run(Boot.java:232)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)

**Comment by justicengom** [comment]
Hi
After following step from @pvanheus comment, I wanted to check if Quanttb is running well with data from exdata.
this is the first message from my screen :
Getting bam file and pileup for exdata/readset1.fq exdata/readset2.fq
ERROR: Some sample files don't exist:
output1/temp/readset1.vcf

then I went through the document :
cat readset1.log
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 396040 sequences (40000040 bp)...
[M::process] read 38846 sequences (3923446 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 193080, 42, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (192, 198, 205)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (166, 231)
[M::mem_pestat] mean and std.dev: (198.49, 9.98)
[M::mem_pestat] low and high boundaries for proper pairs: (153, 244)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (3, 11, 383)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1143)
[M::mem_pestat] mean and std.dev: (75.00, 150.93)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1523)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 396040 reads in 33.368 CPU sec, 8.406 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 18958, 8, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (191, 198, 205)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (163, 233)
[M::mem_pestat] mean and std.dev: (198.39, 10.02)
[M::mem_pestat] low and high boundaries for proper pairs: (149, 247)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 38846 reads in 4.592 CPU sec, 1.022 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 4 /home/justicengom/miniconda3/envs/quanttb/lib/python2.7/site-packages/quanttb/data/GCF_000277735.2_ASM27773v2_genomic.fna exdata/readset1.fq exdata/readset2.fq
[main] Real time: 10.048 sec; CPU: 38.558 sec
java.util.zip.ZipException: invalid entry CRC (expected 0xdb44c871 but got 0x3ec1653d)
at java.base/java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:408)
at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
at java.base/java.util.jar.JarInputStream.read(JarInputStream.java:207)
at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:119)
at java.base/java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
at java.base/java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
at com.simontuffs.onejar.Boot.findJarEntry(Boot.java:443)
at com.simontuffs.onejar.Boot.getMyJarPath(Boot.java:415)
at com.simontuffs.onejar.Boot.run(Boot.java:232)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
Boot: Warning: jar=null loaded from java.class.path (/home/justicengom/miniconda3/envs/quanttb/lib/python2.7/site-packages/quanttb/data/pilon-1.22.jar)
Exception in thread "main" java.lang.IllegalArgumentException: Unable to locate com.simontuffs.onejar.Boot in the java.class.path: consider using -Done-jar.jar.path to specify the one-jar filename.
at com.simontuffs.onejar.Boot.getMyJarPath(Boot.java:434)
at com.simontuffs.onejar.Boot.run(Boot.java:232)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
