### ISSUE TITLE
Other parasite or pathogen

### ISSUE THREAD

**Issue by Rajmandage22** [AbeelLab/quanttb#8]
Is quanttb methodology useful to identify and quantify individual strains present in other parasite or pathogen?

**Comment by thomasabeel** [comment]
You could probably use it if the genomes of this parasite or pathogen has sufficient similarities. 

However, I would recommend you use another tool that we recently developed that is probably better suited to the task. 

https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02630-0

**Comment by Rajmandage22** [comment]
StrainGE looks promising. Thank you so much for your update on my query.
